version: "3"

networks:
  dev:
    driver: bridge
    name: dev

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    restart: unless_stopped

  backend:
    container_name: backend
    restart: unless_stopped
    build:
      context: ./server
    networks:
      - dev
  
  frontend:
    container_name: frontend
    restart: unless_stopped
    build:
      context: ./client
    networks:
      - dev