@startuml backend 1

start
:Получение желаемого района,
списка достопримечательностей,
дата заезда и выезда
(район.name, достоприм.name,
заезда.date, выезд.date);

:Отправка запроса к Postgres
(район.name, достоприм.name);

:Получение ID достопримечательностей
и ID всех гостиниц указанного района
(достоприм.id, гостиница.id);

if (Путешествие на машине?\n(Применение эвристики)) then (Да)
    :"Отбросить"
    аномальные точки;
    else (Нет)
        :Ориентироваться на "лучшую"
        общественно-транспортную 
        развязку;
    endif

:Получение ID достопримечательностей
и ID подходящих гостиниц указанного района
(достоприм.id, гостиница.id);

:Отправка запроса в расчетный модуль
(достоприм.id, гостиница.id);

:Получение и сохранение
готового решения в Postgres
(гостиница.id);

:Вывод решения (после выбора гостиницы)
(гостиница.id, достоприм.id);

stop
@enduml
