@startuml алгоритм_расчетного_модуля

start
:Получение списка ID гостиниц,
достопримечательностей
и ограничений;

while (Гостиница in Список\nгостиниц)

    :Получение матрицы 
    расстояний
    (гостиница.id, 
    достоприм-ти.id);

    :Маршрут обхода 
    достоприм-ей = Оптимизатор
    (матрица расстояний,
    стартовая точка (гостиница),
    ограничения);
    
    if (Маршрут пустой?) then (Да)
    else (Нет)
        :Занести гостиницу в 
        список подходящих;
    endif

endwhile
:Вывод списка подходящих 
гостиниц;

stop
@enduml
