@startuml Алгоритм полного перебора

start
:Инициализация матрицы расстояний;

:Ввод N, M;

:K = N!
Q = 99999;

:Инициализация множества для записи уникальных путей (1);

while (L = 1, M, 1)
    
    while (I = 1, K, 1)

        while (ID достопримечательностей: все ID)

        :Построить связь до достопримечательности;

        :Сохранить путь;

        :"Удалить" ID использованной достопримечательности;


        if (Все достопримечательности\nиспользованы?) then (Да)
        
            if (Путь уникален?) then (Да)
                :Записать путь в множество для записи уникальных путей (1);
                
                if (Текущее расстояние\nпути < Q?) then (Да)
                    :Q = текущее расстояние;
                    
                    :Сохранить результат (путь и расстояние пути);
                    
                    
                else (Нет)
                    
                endif

            else (Нет)
                
            endif
            :Сбросить путь;
        else (Нет)
        endif
        endwhile


    endwhile
    : Вывод пути и его расстояния;

    : "Удалить" ID использованной гостиницы;
endwhile
stop
@enduml
