@startuml пользовательский_интерфейс

skinparam Linetype ortho
skinparam packageStyle Rectangle
skinparam PackageTitleAlignment left

package "Форма авторизации" {
  [Форма авторизации] --> [Форма авторизации пользователя]
  [Форма авторизации] --> [Форма авторизации администратора]
  [Форма авторизации] <--> [Отказ авторизации]
  [Форма авторизации пользователя] --> [Главная страница]
  [Форма авторизации администратора] --> [Панель управления администратора]

' Форма авторизации - форма
' Отказ авторизации - форма + кнопка закрытия (в ней)
}

package "Контакты" {
  [Контакты] <--> [Информация о разработчике]
  [Контакты] <--> [Контакты поддержки]
  [Назад (от "Контакты")] --> [Главная страница]

' Контакты - форма
' Информация о разработчике, Контакты поддержки - форма + кнопка закрытия (в ней)
' Назад - кнопка
}

package "Справка" {
  [Справка] <--> [О программе]
  [Справка] <--> [Руководство пользователя]
  [Назад (от "Справка")] --> [Главная страница]

' Справка - форма
' О программе, Руководство пользователя - форма + кнопка закрытия (в ней)
' Назад - кнопка
}

package "Главная страница" {
  [Главная страница] --> [Справка]
  [Главная страница] --> [Контакты]
  [Поиск\n\nДата заезда-выезда,\nГород] <--> [Категории\n\n(Поесть,\nПосмотреть)]
  [Поиск\n\nДата заезда-выезда,\nГород] <--> [Район]
  [Категории\n\n(Поесть,\nПосмотреть)] <--> [Список гостиниц]
  [Район] <--> [Список гостиниц]
  [Список гостиниц] <--> [Визуализация маршрута]
  [Список гостиниц] <--> [Бронирование]
  [Авторизация] --> [Форма авторизации]
  [Бронирование] --> [Форма авторизации пользователя]
  [Главная страница] --> [Форма авторизации администратора]

' Главная страница, Поиск - форма
' Справка, Контакты, Выход - кнопка
}

@enduml
