@startuml пользовательский_интерфейс

package "Форма авторизации" {
  [Форма авторизации] <--> [Отказ авторизации]
  [Форма авторизации] --> [Главная страница]

' Форма авторизации - форма
' Отказ авторизации - форма + кнопка закрытия (в ней)
}

package "Главная страница" {
  [Главная страница] --> [Справка]
  [Главная страница] --> [Контакты]
  [Поиск\n\nДата заезда-выезда,\nГород] <--> [Категории\n\nПоесть,\nПосмотреть]
  [Категории\n\nПоесть,\nПосмотреть] <--> [Районы]
  [Районы] <--> [Список гостиниц]
  [Список гостиниц] <--> [Визуализация маршрута]
  [Выход] --> [Форма авторизации]

' Главная страница, Поиск - форма
' Справка, Контакты, Выход - кнопка
}

package "Контакты" {
  [Контакты] <--> [Информация о разработчике]
  [Контакты] <--> [Контакты поддержки]
  [Назад (от "Контакты")] --> [Главная страница]

' Контакты - форма
' Информация о разработчике, Контакты поддержки - форма + кнопка закрытия (в ней)
' Назад - кнопка
}

package "Справка" {
  [Справка] <--> [О программе]
  [Справка] <--> [Руководство пользователя]
  [Назад (от "Справка")] --> [Главная страница]

' Справка - форма
' О программе, Руководство пользователя - форма + кнопка закрытия (в ней)
' Назад - кнопка
}

@enduml
